// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrdersAndCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdersAndCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201812101839528_Orders-And-Cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
